apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-pod
      app: demo-voting-pod
  template:
    metadata:
      name: db-pod
      labels:
        name: db-pod
        app: demo-voting-pod
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir: {}
