apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-pod
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: demo-voting-pod
  ports:
  - port: 6379
    targetPort: 6379
