apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-pod
spec:
  type: NodePort
  selector:
    name: result-app-pod
    app: demo-voting-pod
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001
