apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-pod
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-pod
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:before
          ports:
          - containerPort: 80
