apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-pod
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-pod
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker
        command: ["sh", "-c", "while true; do echo Hello, Kubernetes!; sleep 10; done"]
